apiVersion: v2
appVersion:  v0.0.1
dependencies:
- alias: vm
  condition: vm.enabled
  name: victoria-metrics-k8s-stack
  repository: https://victoriametrics.github.io/helm-charts/
  tags:
  - monitoring
  version: 0.44.0
description: A Helm chart for victoria
name: vm
version: 0.0.1